/**
 * This file contains the data layer for the authentication module.
 *
 * Do NOT edit this file.
 */

const users: Record<string, string> = {
  admin: "admin",
};

export const validateCredentials = (
  user: string,
  password: string
): boolean => {
  if (!user || !password) {
    return false;
  }

  return users[user] === password;
};

type CreateUserObj = {
  user: string;
  password: string;
};

export const createUser = (data: CreateUserObj): number => {
  if (data.user in users) {
    throw new Error("User already exists");
  }

  users[data.user] = data.password;

  return Object.keys(users).length;
};

export const changePassword = (user: string, newPassword: string): void => {
  // TODO: one should probably add password strength verification here (length, use special chars, etc ...)
  users[user] = newPassword;
};
